apiVersion: v1
kind: Service
metadata:
  name: productivity-api-server-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: api-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80