apiVersion: v1
kind: Service
metadata:
  name: productivity-api-server-service
spec:
  selector:
    app: api-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800