apiVersion: apps/v1
kind: Deployment
metadata:
  name: productivity-api-server-deployment
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: volgenic/productivity-api-server:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP